/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "inverse-surface": "#28332c",
        "background": "#f1fcf2",
        "surface": "#f1fcf2",
        "on-secondary-fixed-variant": "#00522d",
        "surface-variant": "#dae5dc",
        "secondary-container": "#97f3b5",
        "secondary-fixed-dim": "#7ed99e",
        "tertiary-container": "#855300",
        "tertiary": "#653e00",
        "surface-container": "#e5f1e7",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed-dim": "#88d7a8",
        "primary": "#005131",
        "surface-container-highest": "#dae5dc",
        "on-secondary": "#ffffff",
        "secondary": "#006d3d",
        "on-primary-container": "#99e9b9",
        "outline-variant": "#bfc9c0",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed": "#a4f4c3",
        "inverse-primary": "#88d7a8",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#002111",
        "on-surface-variant": "#3f4942",
        "on-secondary-container": "#047240",
        "surface-bright": "#f1fcf2",
        "on-surface": "#141e18",
        "on-tertiary-fixed": "#2a1700",
        "surface-dim": "#d1ddd3",
        "on-tertiary-container": "#ffd099",
        "primary-container": "#176b45",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#00210f",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-low": "#ebf7ed",
        "on-tertiary": "#ffffff",
        "outline": "#6f7a71",
        "surface-tint": "#186c45",
        "surface-container-high": "#e0ebe1",
        "on-primary-fixed-variant": "#005232",
        "inverse-on-surface": "#e8f4ea",
        "secondary-fixed": "#9af6b8",
        "on-background": "#141e18",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "layout-margin-mobile": "1rem",
        "space-2xl": "2rem",
        "space-xxs": "0.25rem",
        "touch-target-min": "3rem",
        "space-sm": "0.75rem",
        "layout-margin-desktop": "2rem",
        "layout-margin-tablet": "1.5rem",
        "layout-gutter": "1rem",
        "space-md": "1rem",
        "space-xl": "1.5rem",
        "space-lg": "1.25rem",
        "space-3xl": "3rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope"],
        "headline-sm": ["Manrope"],
        "body-sm": ["Manrope"],
        "headline-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "label-md": ["Manrope"],
        "headline-xl": ["Manrope"],
        "headline-xl-mobile": ["Manrope"],
        "label-sm": ["Manrope"],
        "title-md": ["Manrope"],
        "label-lg": ["Manrope"],
        "body-lg": ["Manrope"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0.005em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
